package org.fsu.cs.capstone.personalweatherapplication.controllers;

import org.fsu.cs.capstone.personalweatherapplication.repositories.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.fsu.cs.capstone.personalweatherapplication.models.User;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import org.json.*;

@Controller // This means that this class is a Controller
@RequestMapping(path = "/user") // This means URL's start with /demo (after Application path)
public class UserController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    // FOR TESTING PURPOSES
    @PostMapping(path = "/create")
    public @ResponseBody String createUser(@RequestBody String userValues) {
        JSONObject obj = new JSONObject(userValues);
        String name = obj.getString("username");
        String password = obj.getString("password");
        User n = new User();
        n.setName(name);
        n.setPassword(password);
        userRepository.save(n);
        return "OK";
    }

    @GetMapping(path = "/all")
    public @ResponseBody Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }

}
